name: Test1
on:
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.6.3
    - run: |
        mvn clean package
    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v1
      with:
        application_id: ${{ secrets.APPLICATION_ID }}
        application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'
        token: ${{ steps.get_workflow_token.outputs.token }}

    - uses: LouisBrunner/checks-action@v1.1.1
      with:
        token: ${{ steps.get_workflow_token.outputs.token }}
        name: Test With Actions
        conclusion: success
        action_url: https://example.com/action
        details_url: https://example.com/details
        actions: |
          [{"label":"Click Me","description":"Click me to get free RAM","identifier":"sent_to_webhook"}]
