name: Test3

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: maven-test-${{ hashFiles('**/pom.xml') }}
        restore-keys:
          maven-test-

    - name: Build with Maven
      run: mvn package -B

    - name: Clean cache
      run: |
        find ~/.m2/repository -type d -name '*SNAPSHOT' | xargs rm -fr
